export const APP_BOOT_SUCCESS = 'APP_BOOT_SUCCESS';
export const APP_BOOT_FAILURE = 'APP_BOOT_FAILURE';

export const FETCH_SCHEDULE_LOGS_SUCCESS = 'FETCH_SCHEDULE_LOGS_SUCCESS';
export const FETCH_SCHEDULE_LOGS_FAILURE = 'FETCH_SCHEDULE_LOGS_FAILURE';
